-- 코드를 입력하세요
WITH HEAVY_USER as (
    SELECT HOST_ID, COUNT(*) as count
    FROM PLACES 
    GROUP BY HOST_ID HAVING COUNT(*) >= 2
)

SELECT P.ID, P.NAME, P.HOST_ID
FROM PLACES P, HEAVY_USER H
WHERE P.HOST_ID = H.HOST_ID;