-- 코드를 입력하세요
SELECT O.PRODUCT_ID, P.PRODUCT_NAME, SUM(O.AMOUNT*P.PRICE) as TOTAL_SALES
FROM FOOD_ORDER O
JOIN FOOD_PRODUCT P ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE TO_CHAR(O.PRODUCE_DATE, 'YYYY-MM') = '2022-05'
GROUP BY O.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY SUM(O.AMOUNT*P.PRICE) DESC, O.PRODUCT_ID;