-- 코드를 입력하세요
SELECT '/home/grep/src/' || BOARD_ID || '/' || FILE_ID || FILE_NAME || FILE_EXT as FILE_PATH
FROM USED_GOODS_FILE
WHERE BOARD_ID IN (
    SELECT board_id
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    FETCH first 1 ROWS ONLY
)
ORDER BY FILE_ID DESC;